title: iFactorial
email: SOON@ifactorial.in
description: >-
  Just my ramblings on math & some related stuff
baseurl: ""
url: "ifactorial.in"
github_username:  plutoniumm

# Pagination
paginate: 8
paginate_path: /:num/

theme: minima

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

include: ['_pages', assets]

exclude:
  - .*-cache/
  - gemfiles/
  - Gemfile*
  - node_modules/
  - vendor/bundle/

# Other
markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false